## GOAL:
##  Report results of a the fit of location-scale model using <LocationScaleFit>
##
## INPUT:
##  obj.fit: object generated by <LocationScaleFit>
##
## OUTPUT:
##  Print estimation results of
##     Fixed effect estimation for Location and Dispersion
##     Effective dimensions of additive components for Location and Dispersion (if any)
##     Remind the number of B-splines used to estimate the error density and/or the additive components
##     Indicated the required computation time
##
## -----------------------------------
## Philippe LAMBERT (ULiege, Oct 2018
## Email:  p.lambert@uliege.be
## Web: http://www.statsoc.ulg.ac.be
## -----------------------------------
#' Print summary information on a fitted Double Additive Location-Scale Model (DALSM) from a DALSM object
#'
#' @usage \method{print}{DALSM}(x,...)
#'
#' @param x an object of class \code{\link{DALSM.object}}
#' @param ... additional generic printing arguments
#'
#' @details Provides summary measures on the estimation of the regression parameters and additive terms
#' in the location and dispersion submodels corresponding to a \code{\link{DALSM.object}} generated by \code{\link{DALSM}}
#'
#' @author Philippe Lambert \email{p.lambert@uliege.be}
#'
#' @seealso \code{\link{DALSM}}, \code{\link{DALSM.object}}, \code{\link{plot.DALSM}}
#'
#' @export
#'
print.DALSM = function(x,...){
  obj.fit = x
  cat("\n-----------------------------------------------------------------------\n")
  cat("                Double Additive Location-SCALE Model \n")
  cat("-----------------------------------------------------------------------\n")
  if (obj.fit$REML){
    cat("*** REML-type estimation ***\n")
  }
  cat("Fixed effects for Location:\n")
  print(round(obj.fit$fixed.loc,3))
  J1 = obj.fit$regr1$J
  if (J1 > 0){
    cat("\n",length(obj.fit$ED1[,1])," additive term(s) in Location: Eff.dim / Test No effect or Linearity\n",sep="")
    print(round(obj.fit$ED1,3))
  }
  cat("\nFixed effects for Dispersion:\n")
  print(round(obj.fit$fixed.disp,3))
  J2 = obj.fit$regr2$J
  if (J2 > 0){
    cat("\n",length(obj.fit$ED2[,1])," additive term(s) in Dispersion: Eff.dim / Test No effect or Linearity\n",sep="")
    print(round(obj.fit$ED2,3))
  }
  ##
  cat("\n")
  if (J1 > 0) cat(obj.fit$K1,"  B-splines per additive component in location\n",sep="")
  if (J2 > 0) cat(obj.fit$K2,"  B-splines per additive component in dispersion\n",sep="")
  if (obj.fit$Normality) cat("Normality assumed for the error density\n")
  else cat(obj.fit$K.error," B-splines for the error density on (",round(obj.fit$rmin,2),",",round(obj.fit$rmax,2),")\n",sep="")
  message(sprintf("\nTotal sample size: %s ; Credible level for CI: %s",obj.fit$n,1-obj.fit$alpha))
  message(sprintf("Uncensored data: %s (%s percents)",obj.fit$n.uncensored,round(100*obj.fit$n.uncensored/obj.fit$n,2)))
  message(sprintf("Interval Censored data: %s (%s percents)",obj.fit$n.IC,round(100*sum(obj.fit$n.IC)/obj.fit$n,2)))
  message(sprintf("Right censored data: %s (%s percents)",obj.fit$n.RC,round(100*obj.fit$n.RC/obj.fit$n,2)))
  cat("\n-----------------------------------------------------------------------\n")
  cat("Convergence status:",obj.fit$converged,"\n")
  cat("Elapsed time: ",round(obj.fit$elapsed.time,1)," seconds  (",obj.fit$iter," iterations)\n",sep="")
  cat("-----------------------------------------------------------------------\n")
}
